import styles from '@styles/app.module.scss'
import Head from 'next/head'
import React from 'react'
import Nav from './composables/Nav'

interface LayoutProps {
    header?: string
}

const Layout: React.FC<LayoutProps> = ({ header, children }) => {
    return (
        <>
            <Head>
                <title>Next App {header ? `| ${header}` : ''} </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <div className={styles.container}>
                <main className={styles.main}>
                    {children}
                </main>
            </div>
        </>
    )
}


export default Layout